import {GrowPalette} from "./GrowPalette";
import {GrowColorScheme} from 'styled-components';

export const GrowLightScheme: GrowColorScheme = Object.freeze({
    textNormal: GrowPalette.Neutral90,
    textDarken: GrowPalette.Neutral80,
    textAlt: GrowPalette.Neutral50,
    textInverse: GrowPalette.Neutral10,
    textDisabled: GrowPalette.Neutral40,
    textWarning: GrowPalette.Red70,
    buttonPrimary: GrowPalette.Primary60,
    buttonPrimaryPressed: GrowPalette.Primary80,
    buttonPrimaryDisabled: GrowPalette.Neutral20,
    buttonText: GrowPalette.Neutral90,
    buttonTextDisabled: GrowPalette.Neutral40,
    tabButtonPrimary: GrowPalette.Neutral90,
    radioButtonPrimary: GrowPalette.Neutral90,
    radioButtonPrimaryDisabled: GrowPalette.Neutral40,
    radioButtonSecondary: GrowPalette.Neutral70,
    radioButtonSecondaryDisabled: GrowPalette.Neutral50,
    background: GrowPalette.Neutral00,
    backgroundAlt: GrowPalette.Neutral10,
    backgroundInverse: GrowPalette.Neutral80,
    github: '#24292E',
    baekjoon: '#0076C0',
    dividerNormal: GrowPalette.Neutral20,
    textFieldIcon: GrowPalette.Neutral90,
    textFieldIconDisabled: GrowPalette.Neutral50,
    textFieldPrimary: GrowPalette.Primary80,
    textFieldSecondary: GrowPalette.Neutral30,
    textFieldSecondaryDisabled: GrowPalette.Neutral20,
    textFieldTextDisabled: GrowPalette.Neutral40,
    avatarLabel: GrowPalette.Neutral30,
    avatarBackground: GrowPalette.Neutral20,
    elevationBlack1: 'rgba(0, 0, 0, 0.02)',
    elevationBlack2: 'rgba(0, 0, 0, 0.04)',
    elevationBlack3: 'rgba(0, 0, 0, 0.06)',
    bottomTabPrimary: GrowPalette.Neutral70,
    bottomTabPrimaryDisabled: GrowPalette.Neutral40,
    bottomTabSecondary: GrowPalette.Neutral30,
    likePrimary: GrowPalette.Red60,
    likePrimaryDisabled: GrowPalette.Neutral40,
    likeSecondary: GrowPalette.Red10,
    likeSecondaryDisabled: GrowPalette.Neutral20,
});

export const GrowDarkScheme: GrowColorScheme = {
    textNormal: GrowPalette.Neutral10,
    textDarken: GrowPalette.Neutral50,
    textAlt: GrowPalette.Neutral60,
    textInverse: GrowPalette.Neutral10,
    textDisabled: GrowPalette.Neutral40,
    textWarning: GrowPalette.Red60,
    buttonPrimary: GrowPalette.Primary60,
    buttonPrimaryPressed: GrowPalette.Primary80,
    buttonPrimaryDisabled: GrowPalette.Neutral70,
    buttonText: GrowPalette.Neutral90,
    buttonTextDisabled: GrowPalette.Neutral60,
    tabButtonPrimary: GrowPalette.Primary60,
    radioButtonPrimary: GrowPalette.Primary60,
    radioButtonPrimaryDisabled: GrowPalette.Neutral60,
    radioButtonSecondary: GrowPalette.Neutral20,
    radioButtonSecondaryDisabled: GrowPalette.Neutral50,
    background: GrowPalette.Neutral80,
    backgroundAlt: GrowPalette.Neutral90,
    backgroundInverse: GrowPalette.Neutral00,
    github: GrowPalette.Neutral10,
    baekjoon: GrowPalette.Neutral10,
    dividerNormal: GrowPalette.Neutral70,
    textFieldIcon: GrowPalette.Primary60,
    textFieldIconDisabled: GrowPalette.Primary30,
    textFieldPrimary: GrowPalette.Primary80,
    textFieldSecondary: GrowPalette.Neutral70,
    textFieldSecondaryDisabled: GrowPalette.Neutral70,
    textFieldTextDisabled: GrowPalette.Neutral70,
    avatarLabel: GrowPalette.Neutral80,
    avatarBackground: GrowPalette.Neutral70,
    elevationBlack1: 'rgba(204, 204, 214, 0.02)',
    elevationBlack2: 'rgba(204, 204, 214, 0.04)',
    elevationBlack3: 'rgba(204, 204, 214, 0.06)',
    bottomTabPrimary: GrowPalette.Primary40,
    bottomTabPrimaryDisabled: GrowPalette.Neutral60,
    bottomTabSecondary: GrowPalette.Neutral70,
    likePrimary: GrowPalette.Red60,
    likePrimaryDisabled: GrowPalette.Neutral40,
    likeSecondary: GrowPalette.Transparent,
    likeSecondaryDisabled: GrowPalette.Neutral80,
}